import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Gnb } from "@/components/layout/Gnb";
import { ToasterProvider } from "@/providers/ToasterProvider";
import { QueryProvider } from "@/providers/QueryProvider";
import { MemberProvider } from "@/providers/MemberProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="bg-background text-foreground font-pretendard antialiased"
        suppressHydrationWarning
      >
        <QueryProvider>
          <MemberProvider>
            <Gnb />

            <ToasterProvider />
            <main className="mx-auto w-full max-w-[1200px] px-6 sm:px-8">
              {children}
            </main>
          </MemberProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
